<html lang="en">
    <head>
        <meta charset="utf-8">
		<title>Around The NBA</title>
		<link rel="stylesheet" type="text/css" href="style.css">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>

		<style>
			body{padding:0;margin:0; font-family: arial,tahoma,serif; color:#fff;}
			h1{padding: 20px 10px; margin:0;}
			.container{width: 1000px; margin:0 auto; background: #444;}
			.wrap{width:950px; margin: 0 auto; background: #434343; min-height: 200px;}
			.controls{width:950px; margin: 0 auto; min-height: 100px;}
			.controls a{display: inline-block; padding:4px 10px; background: #888; border: 1px solid #d8d8d8; text-decoration: none;}
			.controls input[type=button], .input-right input[type=submit]{padding:3px 6px; min-width: 100px;}			
			p.success{display: block; background: #C6F995; color:#4C930A; border:1px solid #4C930A; padding:10px 50px; margin-bottom: 20px;}	
			p.notice{display: block; background: #F7E079; color:#898004; border:1px solid #898004; padding:10px 50px; margin-bottom: 20px;}	
			.input-row{min-height: 40px;}
			.input-left{display: inline-block; text-align: right; width:150px; vertical-align: top;}
			.input-left span{margin-right: 10px; display: block; }
			.input-right{display: inline-block; text-align: left;}
			.input-right input[type=file],.input-right input[type=text]{padding:3px 6px; width: 250px; margin-bottom: 2px;}
			.input-right input[type=file]{border:none; }
			.input-right textarea{padding:3px 6px; width: 250px; height: 50px; margin-bottom: 15px;}
			.input-right textarea.fullcontent{padding:3px 6px; width: 700px; min-height: 300px;}
			.controls input[type=button], .input-right input[type=submit]{padding:3px 6px; min-width: 100px;}
			
		</style>
	</head>
	<body>		
		<?php include "header.php"; ?>	
		<div class='container'>			
			<div class='header'>

			</div>
			<div>
				<h1>Addnew - Story</h1>
				<div class='wrap'>
					<?php if(isset($notice)): ?>
					<p class='<?php echo $notice['type']; ?>'><?php echo $notice['message']; ?></p>
					<?php endif; ?>
					<form method='POST' action="" enctype="multipart/form-data">
						<div class='input-row'>
							<span class='input-left'>
								<span><label for='title'>Title:</label></span>
							</span>
							<span class='input-right'>
								<span><input type='text' id='title' name='title' maxlength='255' placeholder="Input Podcast Title here" required /></span>								
							</span>
						</div>
						<div class='input-row'>
							<span class='input-left'>
								<span><label for='excerpt'>Excerpt:</label></span>
							</span>
							<span class='input-right'>
								<span><textarea id='excerpt' name='excerpt' maxlength='255' placeholder="Input Excerpt here" required ></textarea></span>								
							</span>
						</div>
						<div class='input-row'>
							<span class='input-left'>
								<span><label for='content'>Content:</label></span>
							</span>
							<span class='input-right'>
								<span><textarea class='fullcontent' id='content' name='content' placeholder="Input Content here" ></textarea></span>								
							</span>
						</div>
						<div class='input-row'>
							<span class='input-left'>
								<span><label for='image-file'>Image:</label></span>
							</span>
							<span class='input-right'>
								<span><input type='file'  id='image-file' name='image-file' required /> 150x150 pixel</span>								
							</span>
						</div>
						<div class='input-row'>
							<span class='input-left'>
								<span><label for='writer'>Writer:</label></span>
							</span>
							<span class='input-right'>
								<span>
									<input type='text'  id='writer' name='writer' placeholder="Input column writer name" maxlength='255' required />
									<input type='hidden' id='writer_id' name='writer_id' value="0"/>
									<input type='button' value='Select Author' id='select-author' />
								</span>	
															
							</span>
						</div>
						<div class='input-row'>
							<span class='input-left'>
								<span><label for='tags'>Tags:</label></span>
							</span>
							<span class='input-right'>
								<span><input type='text'  id='tags' name='tags' placeholder="Input tags seperated by comma" maxlength='255' required /> Input Tags seperated by comma</span>								
							</span>
						</div>
						
						<div class='input-row'>
							<span class='input-left'></span>
							<span class='input-right'>
								<span><label for='status'><input type='checkbox'  id='status' name='status'/> Status(Enable/Disable)</label></span>								
							</span>
						</div>
						<div class='input-row'>
							<span class='input-left'></span>
							<span class='input-right'>
								<span><input type='submit' name='addnew' value='Save Addnew'></span>								
								<span class='controls'><input type='button' value='Cancel' onclick="javascript:document.location.href='around-the-nba.php'"/></span>								
							</span>
						</div>
					</form>
				</div>
			</div>
			<div class='footer'></div>
		</div>		
		<div id='dialog'></div>
		<script>
			$(document).ready(function(){
				$("div[id=dialog]").dialog({
						title:"Authors",
						modal:true,
						width:980,
						height:600,
						position: {
						   my: "center",
						   at: "top",						   
						   of: window
						},
						resizable:false,
						draggable:false,
						dialogClass:'form-dialog',
						buttons:[
							{
								text: "Close",
								click:function(btn){									
									$(this).dialog("close");
								}		
							},
							{
								text:"Add Author",
								click:function(btn){
									if(btn.target.textContent == "Add Author"){
										$.ajax({
											url:"/admin/around-the-nba/ajax.php?request=formAddAuthors",
											cache:false
										}).done(function(retHtml){
											$("div[id=dialog]").html(retHtml).dialog("open");
										});
										$(".form-dialog .ui-button-text:contains('Add Author')").text('Save');
									}else{
										//alert($("#writter-fullname").val());
										
										var oData = new FormData(document.forms.namedItem("writer-form"));
 
										$.ajax({
											type:"POST",
											contentType:false,
											processData:false,											
											cache:false,
											url:"/admin/around-the-nba/ajax.php?request=submitAddAuthor",
											data:oData,
											success:function(data){
												/*console.log(data);*/
												$.ajax({
													url:"/admin/around-the-nba/ajax.php?request=getAllAuthors",
													cache:false
												}).done(function(retHtml){
													$("div[id=dialog]").html(retHtml).dialog("open");
												});
												$(".form-dialog .ui-button-text:contains('Save')").text('Add Author');		
											}
										});
										
									}	
								}
							}
						]				
					}).dialog("close");
				$("input[id=select-author]").click(function(){
					$(".form-dialog .ui-button-text:contains('Save')").text('Add Author');
					$.ajax({
						url:"/admin/around-the-nba/ajax.php?request=getAllAuthors",
						cache:false
					}).done(function(retHtml){
						$("div[id=dialog]").html(retHtml).dialog("open");
					});					
				});
				
			});
		</script>
		<script type="text/javascript" src="tiny_mce/tiny_mce.js"></script>
		<script type="text/javascript">
			<!--
			tinyMCE.init({
			   mode : "exact",
			   elements : "content",
			   theme : "advanced",
			   /*relative_urls : false,
			   convert_urls : true,
			   remove_script_host : false,*/
			   relative_urls : false,
			   convert_urls : true,
			   remove_script_host : false,
			   plugins : "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
			   theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,cut,copy,pasteword,|,undo,redo,|,link,unlink,|,bullist,numlist,|,forecolor",
			   theme_advanced_buttons2 : "justifyleft,justifycenter,justifyright,justifyfull,|,image,code",
			   theme_advanced_buttons3 : "",
			   theme_advanced_toolbar_location : "top",
			   theme_advanced_toolbar_align : "left",
			   theme_advanced_statusbar_location : "bottom",
			   theme_advanced_resizing : true
			});
		</script>	
	</body>
</html>