<html lang="en">
    <head>
        <meta charset="utf-8">
		<title>Around The NBA</title>
		<link rel="stylesheet" type="text/css" href="style.css">
		<style>
			body{padding:0;margin:0; font-family: arial,tahoma,serif; color:#fff;}
			h1{padding: 20px 10px; margin:0;}
			.container{width: 1000px; margin:0 auto; background: #444;}
			.wrap{width:950px; margin: 0 auto; background: #434343; min-height: 200px;}
			.controls{width:950px; margin: 0 auto; min-height: 100px;}
			.controls a{display: inline-block; padding:4px 10px; background: #888; border: 1px solid #d8d8d8; text-decoration: none;}
			.controls input[type=button], .input-right input[type=submit]{padding:3px 6px; min-width: 100px;}
			.row-title span{display: inline-block; background:#888; height:40px; vertical-align: top;  border-bottom: 1px solid #fff; margin-bottom: 3px; padding:3px 2px;}
			.row-data span{display: inline-block; background: #484848;padding:3px 2px;}
			.row-data{margin-bottom: 2px;}
			.row-data span a{text-decoration: none; color:#fff;}
			.row-data span a:hover{text-decoration:underline;}
			.row-data span{overflow: hidden; height: 150px;}
			.col-1{width:120px;}
			.col-2{width:200px;}
			.col-3{width:150px; text-align: center;}
			.col-4{width:100px;}
			.col-5{width:120px;}
			.col-6{width:80px;}
			.col-7{width:120px;}
			.col-1 a{color:yellow !important;}
			p.success{display: block; background: #C6F995; color:#4C930A; border:1px solid #4C930A; padding:10px 50px; margin-bottom: 20px;}	
			p.notice{display: block; background: #F7E079; color:#898004; border:1px solid #898004; padding:10px 50px; margin-bottom: 20px;}	
		</style>
	</head>
	<body>		
		<?php include "header.php"; ?>	
		<div class='container'>			
			<div class='header'>

			</div>
			<div class='content'>
				<h1>Around The NBA</h1>
				<div class='wrap'>
					<?php if(isset($notice)): ?>
					<p class='<?php echo $notice['type']; ?>'><?php echo $notice['message']; ?></p>
					<?php endif; ?>
					<div class='row-title'>
						<span class='col-1'>Title</span>
						<span class='col-2'>Exceprt</span>
						<span class='col-3'>Image</span>
						<span class='col-4'>Date Created</span>
						<span class='col-5'>Writer</span>
						<span class='col-6'>Status</span>
						<span class='col-7'>Control</span>
					</div>
					<?php foreach($data as $d): ?>					
					<div class='row-data'>
						<span class='col-1'><?php echo $d['title']; ?></span>
						<span class='col-2'><?php echo $d['excerpt']; ?></span>
						<span class='col-3'><img height='150' src="/ftp-web/around-the-nba/<?php echo $d['image']; ?>" /></span>
						<span class='col-4'><?php echo $d['date_created']; ?></span>
						<span class='col-5'><?php echo $d['writer']; ?></span>
						<span class='col-6'><?php echo ($d['status'] == 1)?"Enabled":"Disabled"; ?></span>
						<span class='col-7'>
							<input type='button' value='Edit' onclick="javascript:document.location.href='around-the-nba.php?edit&id=<?php echo $d['id']; ?>'"/>
							<input type='button' value='Preview' />
						</span>
					</div>
					<?php endforeach; ?>

				</div>				
				<div class='controls'>
					<input type=button value="Add New Story" onclick="javascript:document.location.href='/admin/around-the-nba.php?addnew'" />					
				</div>
			</div>
			<div class='footer'></div>
		</div>
	</body>
</html>